[target.'cfg(target_os = "macos")']
# This is necessary for the dynamic linking to work on macOS
# Otherwise, the symbols won't be available until runtime
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]
