[package]
name = "steam-stuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
link-cplusplus = "1.0.9"

[build-dependencies]
cmake = "0.1.50"
